//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Produccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class di_certificado_decenal
    {
        public int id_reg_cer { get; set; }
        public Nullable<int> id_pv { get; set; }
        public decimal cod_suc { get; set; }
        public decimal cod_ramo { get; set; }
        public decimal nro_pol { get; set; }
        public string txt_nro_pol { get; set; }
        public int cod_item { get; set; }
        public string txt_certificado { get; set; }
        public Nullable<System.DateTime> fec_ini { get; set; }
        public Nullable<System.DateTime> fec_fin_seg { get; set; }
        public Nullable<System.DateTime> fec_fin_tres { get; set; }
        public Nullable<System.DateTime> fec_fin_cinco { get; set; }
        public Nullable<System.DateTime> fec_fin_diez { get; set; }
        public decimal imp_suma_asegurada { get; set; }
        public decimal imp_admon_riesgos { get; set; }
        public decimal imp_prima_neto_end { get; set; }
        public decimal imp_prima_neta_real { get; set; }
        public decimal imp_prima_hab { get; set; }
        public decimal imp_prima_seg { get; set; }
        public decimal imp_prima_3 { get; set; }
        public decimal imp_prima_4 { get; set; }
        public decimal imp_millar { get; set; }
        public string txt_nombre { get; set; }
        public string txt_RFC { get; set; }
        public string txt_NSS { get; set; }
        public string txt_desarrollo { get; set; }
        public Nullable<decimal> nro_credito { get; set; }
        public string cod_CUV { get; set; }
        public string txt_condominio { get; set; }
        public string txt_calle { get; set; }
        public string nro_exterior { get; set; }
        public string nro_interior { get; set; }
        public string txt_mz { get; set; }
        public string txt_lt { get; set; }
        public string txt_super_mz { get; set; }
        public string txt_edif { get; set; }
        public string txt_nivel { get; set; }
        public string cod_postal { get; set; }
        public string cod_colonia { get; set; }
        public string cod_municipio { get; set; }
        public string cod_entidad { get; set; }
        public string txt_nom_constructor { get; set; }
        public Nullable<System.DateTime> fec_ini_garantia { get; set; }
        public Nullable<System.DateTime> fec_fin_obra { get; set; }
        public Nullable<System.DateTime> fec_adquisicion { get; set; }
        public string txt_nom_notario { get; set; }
        public Nullable<decimal> nro_escritura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> nro_notaria { get; set; }
    }
}
