//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Produccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class di_certificado_lote_decenal
    {
        public int id_reg_cer { get; set; }
        public int nro_lote { get; set; }
        public string txt_certificado { get; set; }
        public string txt_usuario_alta { get; set; }
        public System.DateTime fec_alta { get; set; }
        public string txt_usuario_baja { get; set; }
        public Nullable<System.DateTime> fec_baja { get; set; }
        public string txt_status_cer { get; set; }
    }
}
